# GoodTerminal TWM Configuration

# Where TWM will search for workspaces
search_paths:
  - ~/Documents
  - ~/Projects
  - ~/github
  - ~/work
  - ~/code

# Only show workspaces that have a .twm.yaml file
workspace_definitions:
  - name: "saved"
    has_any_file: [".twm.yaml"]
    default_layout: "saved"

# Maximum depth to search for workspaces
max_search_depth: 3

# Define workspace layouts
layouts:
  - name: "saved"
    commands:
      - "echo 'Loading saved workspace...'"

# Number of path components to use for session names
session_name_path_components: 1

# Path components to exclude from session names
exclude_path_components: []

# Whether to follow symbolic links when searching
follow_links: false